server:
    host: 120.79.138.224  #开发环境
#    host: 47.106.129.1   # 正式环境
    port: 9963

spring:
    application:
        name: grow
    output:
      ansi:
        enabled: always

    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${server.host}:3306/company?useUnicode=true&characterEncoding=utf8&useSSL=false
#      username: root                     #线上账号
#      password: MBJ5xCgLZVntUs57         #线上密码
      username: dev_data
      password: 6b4BnnmiczHEBZGs

    #        RabbitMq 配置
    rabbitmq:
      host: ${server.host}
      port: 5672
      username: guest
      password: guest
      publisher-confirms: false
      virtual-host: /


# 缓存配置
    cache:
      ehcache:
        config: classpath:config/cache.xml
eureka:
    client:
        serviceUrl:
            defaultZone: http://${server.host}:8761/eureka/
    instance:
          prefer-ip-address: true
          ip-address: ${server.host}

#   连接数据库配置
#    datasource:
#       driver-class-name: com.mysql.jdbc.Driver
#       url: jdbc:mysql://120.79.138.224:3306/company?useUnicode=true&characterEncoding=utf8&useSSL=false
#       username: dev_data
#       password: 6b4BnnmiczHEBZGs

# 配置日志
logging:
  config: classpath:config/logback-spring.xml
  levelL: info
  path: ./logs


  redis:
    # Redis服务器地址
      host: ${server.host}
    # Redis服务器连接端口
      port: 6379
    # Redis服务器连接密码（默认为空）
      password:
    # 连接超时时间（毫秒）
      timeout: 0
    # Redis数据库索引（默认为0）
      database: 0
      pool:
      # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      # 连接池中的最大空闲连接
        max-idle: 8
      # 连接池中的最小空闲连接
        min-idle: 0